// DONT TRY TO NAME THE ENDPOINT OF THE URL WITH URL NAME OPERATION BUT ONLY USE HTTP METHODS 


// /addNewTour -->P0ST /tours   ->CREATE

// /getTour --> GET /tours/<tourid> . ->READ

// /updateTour->   |------> PUT   tours/<toursid>     ->UPDATE
                // |------> PATCH tours/<toursid>     -->UPDATE


                // Note:: PUT-->THE CLIENT IS SUPOOSE TO SEND THE ENTIRE OBJECT 
                        //PATCH ->IT IS ONLY SUPPOSED TO SEND TO SEND ONLY THE PART OF THE OBJECT 

// /deleteTour ->   DELETE -> tours/tours<id>         ->DELETE

