// Express is a minimal Node.js framework and a higher level of abstraction 

// EXPRESS JS IS MADE ON TOP OF NODE JS 

// EXPRESS JS IS WRITEEN 100% IN JS CODE 

// EXPRESS CONTAIN A VERY ROBUST SET OF FEATURE ::

// COMPLEX ROUTING 
// EASIER HANDLING OF REQUEST AND RESPONSES 
// MIDDLEWARE
// SERVER-SIDE-RENDERING 

// ROUTING ALLOWED FOR A RAPID DEVELOPMENT OF NODE JS APPLICATION :: WE DONT HAVE TO REINVENT THE WHEEL


// EXPRESS MAKE IT EASIER TO ORGANIZE OUR APPLICATION INTO THE MVC ARCHITECTURE

// MVC -> IS A VERY POWERFUL SOFTWARE ARCHITECTURAL PATTERN 
